### ISSUE TITLE
"cabal install" failed,how to fix it?tks

### ISSUE THREAD

**Issue by luckypoem** [alemedeiros/alemedeiros.github.io#1]
hi.

root@AR:/usr/local# git clone https://github.com/alemedeiros/alemedeiros.github.io
root@AR:/usr/local# cd alemedeiros.github.io
root@AR:/usr/local/alemedeiros.github.io# cabal sandbox init
root@AR:/usr/local/alemedeiros.github.io# cabal install

it shows:
...
Preprocessing executable 'pandoc-citeproc' for pandoc-citeproc-0.9.1.1...
[1 of 3] Compiling Prelude          ( prelude/Prelude.hs, dist/dist-sandbox-b7a506a9/build/pandoc-citeproc/pandoc-citeproc-tmp/Prelude.o )
[2 of 3] Compiling Paths_pandoc_citeproc ( dist/dist-sandbox-b7a506a9/build/autogen/Paths_pandoc_citeproc.hs, dist/dist-sandbox-b7a506a9/build/pandoc-citeproc/pandoc-citeproc-tmp/Paths_pandoc_citeproc.o )
[3 of 3] Compiling Main             ( pandoc-citeproc.hs, dist/dist-sandbox-b7a506a9/build/pandoc-citeproc/pandoc-citeproc-tmp/Main.o )

pandoc-citeproc.hs:64:50:
    No instance for (Num Data.Aeson.Encode.Pretty.Indent)
      arising from the literal ‘2’
    In the ‘confIndent’ field of a record
    In the first argument of ‘encodePretty'’, namely
      ‘Config {confIndent = 2, confCompare = compare}’
    In the second argument of ‘(.)’, namely
      ‘encodePretty' (Config {confIndent = 2, confCompare = compare})’
cabal: Leaving directory '/tmp/cabal-tmp-14837/pandoc-citeproc-0.9.1.1'
cabal: Error: some packages failed to install:
alemedeiros-0.2.0.0 depends on pandoc-citeproc-0.9.1.1 which failed to
install.
hakyll-4.7.5.2 depends on pandoc-citeproc-0.9.1.1 which failed to install.
pandoc-citeproc-0.9.1.1 failed during the building phase. The exception was:
ExitFailure 1
root@AR:/usr/local/alemedeiros.github.io#

how to fix it?
thank you

**Comment by alemedeiros** [comment]
You should use `stack` instead, it is a newer application to manage Haskell dependencies, it is more consistent than cabal, it downloads and builds the dependencies following the project specification, automatically using sandboxing.

To build:
```
stack build
```

To start Hakyll's watch server
```
stack exec homepage watch
```
